# Generated by Django 4.1.7 on 2023-03-13 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shortener', '0002_alter_kirrurl_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('kirr_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.kirrurl')),
            ],
        ),
    ]
